workflows:
  ios-debug-build:
    name: iOS Debug Build
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Build App
        script: flutter build ios --debug --no-codesign
    artifacts:
      - build/ios/iphoneos/Runner.app